import type { AppRole } from "@/lib/constants/roles";
import type { ProgrammeContext } from "@/types/programme";
import type { RoomRegistry } from "@/types/room-hub";

export type ZoneFunction =
  | "accueil_admin"
  | "urgences"
  | "imagerie"
  | "laboratoire"
  | "consultations"
  | "gyneco_obstetrique"
  | "bloc_cesarienne"
  | "sspi"
  | "sterilisation"
  | "hospitalisation"
  | "neonatologie"
  | "pharmacie"
  | "locaux_techniques"
  | "circulation"
  | "vestiaires"
  | "dechets"
  | "vrd_exterieur";

export type RoomLevel = "RDC" | "R+1" | "R+2" | "toiture" | "exterieur";

export type PlanningBaseline = "initial" | "revised" | "actual";

export type RiskLevel = "low" | "medium" | "high" | "critical";

export type MasterIndexLevel = "green" | "orange" | "red";

export interface ProjectSchedule {
  contractStart: string;
  contractEnd: string;
  realisticEnd: string;
  internalTargetEnd: string;
  forecastEnd: string;
  marginDays: number;
  riskLevel: RiskLevel;
}

export interface NassibProject {
  id: string;
  name: string;
  code: string;
  location: string;
  client: string;
  status: "draft" | "active" | "suspended" | "completed" | "archived";
  contractAmount: number;
  budgetConsumed: number;
  progressPlanned: number;
  progressActual: number;
  schedule: ProjectSchedule;
}

export interface WbsPhase {
  id: string;
  code: string;
  name: string;
  sortOrder: number;
  progressPct: number;
  plannedStart: string;
  plannedEnd: string;
}

export interface PlanningTask {
  id: string;
  projectId: string;
  phaseId: string;
  /** Code WBS du planning transmis (ex. 1.5.3) */
  wbsCode?: string;
  lotCode?: string;
  roomCode?: string;
  name: string;
  responsible?: string;
  company?: string;
  status: "not_started" | "in_progress" | "blocked" | "completed" | "cancelled";
  progressPct: number;
  plannedStart: string;
  plannedEnd: string;
  actualStart?: string;
  actualEnd?: string;
  baselineStart: string;
  baselineEnd: string;
  durationDays: number;
  isCritical: boolean;
  isMilestone: boolean;
  hasProof: boolean;
  predecessors: string[];
  alerts: string[];
}

export type ActionTaskOrigin =
  | "manual"
  | "meeting"
  | "report"
  | "budget"
  | "plan_revision"
  | "reserve"
  | "element";

export type ActionTaskPriority = "low" | "normal" | "high" | "critical";

export type ActionTaskStatus =
  | "open"
  | "in_progress"
  | "blocked"
  | "done"
  | "cancelled";

/** Tâche action chantier — générée ou saisie manuellement */
export interface NassibActionTask {
  id: string;
  title: string;
  description: string;
  origin: ActionTaskOrigin;
  sourceId?: string;
  roomCode?: string;
  lotCode?: string;
  responsible: string;
  company: string;
  priority: ActionTaskPriority;
  plannedStart: string;
  dueDate: string;
  status: ActionTaskStatus;
  planningTaskId?: string;
  reserveId?: string;
  procurementId?: string;
  logisticsId?: string;
  testId?: string;
  meetingId?: string;
  autoGenerated: boolean;
  comments?: string;
}

export interface Zone {
  id: string;
  projectId: string;
  code: string;
  name: string;
  function: ZoneFunction;
}

export interface NassibRoom {
  id: string;
  projectId: string;
  zoneId: string;
  code: string;
  name: string;
  level: RoomLevel;
  zoneFunction: ZoneFunction;
  areaM2: number;
  status:
    | "shell"
    | "rough_in"
    | "mep_embedded"
    | "finishes"
    | "equipment"
    | "testing"
    | "ready_handover"
    | "handover"
    | "occupied";
  progressPct: number;
  lots: string[];
  checklistDone: number;
  checklistTotal: number;
  equipmentCount: number;
  reservesOpen: number;
  validationStatus: "pending" | "partial" | "validated";
  needs: {
    cfo: boolean;
    cfa: boolean;
    cvc: boolean;
    plumbing: boolean;
    medicalGas: boolean;
    furniture: boolean;
    ssi: boolean;
  };
}

export interface MepLot {
  id: string;
  projectId: string;
  code: string;
  name: string;
  trade: string;
  company: string;
  responsible: string;
  progressPct: number;
  documentsValidated: number;
  documentsTotal: number;
  zonesImpacted: string[];
  reservesOpen: number;
  intermediateTestsDone: number;
  intermediateTestsTotal: number;
  finalTestsDone: number;
  finalTestsTotal: number;
  doeStatus: "missing" | "partial" | "complete";
  receptionPvStatus: "none" | "partial" | "signed";
}

export interface MedicalGasNetwork {
  id: string;
  type: "O2" | "vacuum" | "medical_air" | "N2O";
  source: string;
  technicalRoom: string;
  outletsPlanned: number;
  outletsInstalled: number;
  progressPct: number;
  checklist: Record<string, boolean>;
}

export type InventoryKind =
  | "biomedical"
  | "medical_furniture"
  | "office_furniture";

/** Sous-famille mobilier médical — plan implantation K'BIO */
export type MedicalFurnitureGroup =
  | "lit_brancard"
  | "chambre_patient"
  | "soins_support"
  | "tables_cliniques"
  | "autre";

export type InstallPhase =
  | "rough_in"
  | "mep_embedded"
  | "finishes"
  | "commissioning";

/** Jalons chantier — ordonnancement MEP / faux plafonds / équipements */
export type ConstructionGate =
  | "before_mep_embedded"
  | "before_false_ceiling"
  | "before_cvc_final"
  | "before_ssi_final"
  | "after_finishes"
  | "commissioning";

export interface NassibEquipment {
  id: string;
  assetCode: string;
  name: string;
  service: string;
  roomCode?: string;
  inventoryKind: InventoryKind;
  /** Présent si inventoryKind === medical_furniture */
  medicalFurnitureGroup?: MedicalFurnitureGroup;
  brand: string; /** Saisie utilisateur uniquement — jamais pré-rempli */
  model: string; /** Saisie utilisateur uniquement — jamais pré-rempli */
  qty: number;
  supplier: string;
  unitPrice?: number | null;
  status:
    | "to_define"
    | "spec_pending"
    | "validated"
    | "ordered"
    | "manufacturing"
    | "in_transit"
    | "customs"
    | "delivered"
    | "installed"
    | "tested"
    | "commissioned"
    | "accepted"
    | "blocked";
  prerequisitesMet: boolean;
  installPhase: InstallPhase;
  constructionGate: ConstructionGate;
  mepDependencies: string[];
  constructionNote?: string;
  electricalNeed?: string;
  networkNeed?: boolean;
  plumbingNeed?: boolean;
  medicalGasNeed?: boolean;
  cvcNeed?: boolean;
  expectedDelivery?: string;
  actualDelivery?: string;
}

export interface NassibProcurement {
  id: string;
  reference: string;
  lotCode: string;
  description: string;
  supplier: string;
  qty: number;
  orderDate?: string;
  expectedDate: string;
  actualDate?: string;
  status: string;
  criticality: "normal" | "high" | "critical";
  planningImpact: boolean;
  responsible: string;
  /** Lien programme — équipement plan K'BIO ou ligne BOQ */
  sourceType: "equipment" | "boq";
  sourceId?: string;
  boqCode?: string;
  roomCode?: string;
  /** Étape processus import Djibouti (1–13) */
  oddStep: number;
  techValidated: boolean;
  proposedRef: string;
  importRequired: boolean;
  /** Montant HT BOQ si ligne liée — jamais inventé */
  boqAmountHt: number | null;
}

export type LogisticsCategory =
  | "clinical_dm"
  | "medical_furniture"
  | "office_furniture"
  | "zone_supply";

export interface NassibLogisticsLine {
  id: string;
  reference: string;
  description: string;
  category: LogisticsCategory;
  /** Lien équipement ou ligne approvisionnement */
  sourceType: "equipment" | "procurement";
  sourceId: string;
  procurementId?: string;
  qty: number;
  /** Zone de transit / stock intermédiaire */
  storageZone: string;
  targetRoomCode: string;
  status: string;
  /** Étape flux interne (0 = en attente import, 1–8 = circuit polyclinique) */
  flowStep: number;
  criticality: "normal" | "high" | "critical";
  plannedTransferDate: string;
  actualTransferDate?: string;
  responsible: string;
}

export type CommissioningPhaseId = "installation" | "commissioning" | "training";

export type CommissioningPhaseStatus =
  | "locked"
  | "pending"
  | "in_progress"
  | "done"
  | "blocked";

export interface CommissioningPhase {
  status: CommissioningPhaseStatus;
  plannedDate?: string;
  actualDate?: string;
  responsible: string;
  notes?: string;
}

export type CommissioningOverallStatus =
  | "waiting_logistics"
  | "in_progress"
  | "ready_for_exploitation"
  | "blocked";

export interface NassibCommissioningLine {
  id: string;
  equipmentId: string;
  assetCode: string;
  description: string;
  roomCode: string;
  inventoryKind: InventoryKind;
  lotCode: string;
  logisticsReady: boolean;
  logisticsId?: string;
  /** Essai système / OPR lié si disponible */
  linkedTestId?: string;
  phases: Record<CommissioningPhaseId, CommissioningPhase>;
  overallStatus: CommissioningOverallStatus;
  progressPct: number;
  openReserves: number;
}

export interface NassibReserve {
  id: string;
  number: string;
  date: string;
  roomCode?: string;
  zone: string;
  lotCode: string;
  company: string;
  title: string;
  description: string;
  severity: "minor" | "major" | "critical";
  type: string;
  correctiveAction: string;
  assignedTo: string;
  dueDate: string;
  status: string;
  blocksReception: boolean;
}

export interface NassibDocument {
  id: string;
  name: string;
  docType: string;
  version: string;
  date: string;
  emitter: string;
  lotCode?: string;
  validationStatus: string;
  isObsolete: boolean;
}

export interface BoqLine {
  id: string;
  lotCode: string;
  code: string;
  description: string;
  unit: string;
  qtyContract: number;
  unitPrice: number;
  qtyExecuted: number;
  qtyValidated: number;
  paymentRequested: number;
  paymentApproved: number;
  paymentPaid: number;
  retentionPct: number;
}

export interface NassibTest {
  id: string;
  system: string;
  zone: string;
  lotCode: string;
  roomCode?: string;
  normReference: string;
  plannedDate: string;
  actualDate?: string;
  responsible: string;
  result: "not_planned" | "planned" | "in_progress" | "conform" | "non_conform" | "retry" | "validated";
  reservesLinked: number;
}

export interface MeetingAction {
  id: string;
  description: string;
  responsible: string;
  dueDate: string;
  status: "open" | "in_progress" | "done" | "overdue";
}

export type MeetingCategory = "chantier" | "technique" | "coordination";

export type MeetingStatus = "planned" | "completed" | "cancelled";

export interface Meeting {
  id: string;
  date: string;
  title: string;
  reference: string;
  category: MeetingCategory;
  status: MeetingStatus;
  location: string;
  participants: string[];
  agenda: string[];
  decisions: string[];
  blockingPoints: string[];
  actions: MeetingAction[];
}

export interface DailyReport {
  id: string;
  date: string;
  weather: string;
  workforce: { company: string; count: number }[];
  worksDone: string;
  zonesWorked: string[];
  incidents: string;
  blockages: string;
  signedBy: string;
}

export interface Risk {
  id: string;
  title: string;
  description: string;
  category: string;
  probability: number;
  impact: number;
  criticality: number;
  responsible: string;
  actionPlan: string;
  dueDate: string;
  status: "open" | "mitigating" | "closed";
}

export interface SiteEvent {
  id: string;
  date: string;
  type: string;
  message: string;
  module: string;
}

export interface MasterIndex {
  score: number;
  level: MasterIndexLevel;
  breakdown: {
    planning: number;
    quality: number;
    procurement: number;
    technical: number;
    financial: number;
    documentation: number;
  };
}

export interface DashboardExtended {
  projectProgressPlanned: number;
  projectProgressActual: number;
  scheduleVarianceDays: number;
  budgetVariancePct: number;
  delayedTasks: number;
  openReserves: number;
  criticalReserves: number;
  documentsPendingValidation: number;
  criticalProcurements: number;
  nextMeeting: string;
  nextMeetingDate: string;
  nextMilestone: string;
  nextMilestoneDate: string;
  masterIndex: MasterIndex;
}

export interface ProjectMemberExtended {
  id: string;
  name: string;
  email: string;
  role: AppRole;
  company?: string;
}


import type { RoomTechnicalSheet } from "@/types/room-sheet";

export interface NassibBundle {
  project: NassibProject;
  schedule: ProjectSchedule;
  phases: WbsPhase[];
  tasks: PlanningTask[];
  /** Tâches action — génération automatique + saisie manuelle */
  actionTasks: NassibActionTask[];
  /** Tâches auto supprimées par l'utilisateur — ne pas regénérer */
  dismissedActionTaskIds: string[];
  zones: Zone[];
  rooms: NassibRoom[];
  /** Fiches techniques modifiables par local */
  roomSheets: Record<string, RoomTechnicalSheet>;
  mepLots: MepLot[];
  medicalGas: MedicalGasNetwork[];
  equipment: NassibEquipment[];
  procurement: NassibProcurement[];
  logistics: NassibLogisticsLine[];
  commissioning: NassibCommissioningLine[];
  reserves: NassibReserve[];
  documents: NassibDocument[];
  boq: BoqLine[];
  tests: NassibTest[];
  meetings: Meeting[];
  dailyReports: DailyReport[];
  risks: Risk[];
  events: SiteEvent[];
  members: ProjectMemberExtended[];
  dashboard: DashboardExtended;
  programme: ProgrammeContext;
  /** Surcharges nom / rôle fonctionnel (code plan inchangé) */
  roomMetaOverrides: Record<
    string,
    { functionalRole?: string; clinicalActivity?: string }
  >;
  roomRegistry: RoomRegistry;
}
