import type { ProgrammeRevision } from "@/types/programme";
import type {
  BoqLine,
  Meeting,
  NassibActionTask,
  NassibReserve,
} from "@/types/nassib";
import {
  DEFAULT_COMPANY,
  DEFAULT_RESPONSIBLE,
  ROLE_OPC,
} from "@/lib/constants/project-roles";

const TODAY = new Date("2026-06-13");

function addDays(iso: string, days: number): string {
  const d = new Date(iso);
  d.setDate(d.getDate() + days);
  return d.toISOString().slice(0, 10);
}

function daysFromNow(days: number): string {
  const d = new Date(TODAY);
  d.setDate(d.getDate() + days);
  return d.toISOString().slice(0, 10);
}

function mergeExisting(
  generated: NassibActionTask[],
  existing: NassibActionTask[],
  dismissedIds: Set<string>,
): NassibActionTask[] {
  const manual = existing.filter((t) => !t.autoGenerated);
  const merged = generated
    .filter((g) => !dismissedIds.has(g.id))
    .map((g) => {
      const prev = existing.find((e) => e.id === g.id);
      if (!prev) return g;
      return {
        ...g,
        status: prev.status,
        comments: prev.comments,
        responsible: prev.responsible || g.responsible,
        dueDate: prev.dueDate || g.dueDate,
      };
    });
  return [...merged, ...manual.filter((m) => !merged.some((g) => g.id === m.id))];
}

const SCOPE_LABELS: Record<ProgrammeRevision["scope"], string> = {
  dispatch: "dispatching locaux",
  equipment: "équipement",
  boq: "BOQ",
  plan: "plan architectural",
};

/**
 * Tâches action — uniquement événements programme (pas le WBS planning).
 * CR, rapports/réserves, validation budget, révisions plan.
 */
export function buildActionTasksFromProject(input: {
  boq: BoqLine[];
  revisions: ProgrammeRevision[];
  reserves: NassibReserve[];
  meetings: Meeting[];
  dismissedIds?: string[];
}): NassibActionTask[] {
  const out: NassibActionTask[] = [];
  const dismissed = new Set(input.dismissedIds ?? []);

  for (const meeting of input.meetings) {
    for (const action of meeting.actions ?? []) {
      if (action.status === "done") continue;
      const id = `auto-meeting-${meeting.id}-${action.id}`;
      if (dismissed.has(id)) continue;
      out.push({
        id,
        title: action.description,
        description: `Action CR — ${meeting.title} du ${meeting.date}`,
        origin: "meeting",
        sourceId: action.id,
        responsible: action.responsible || DEFAULT_RESPONSIBLE,
        company: DEFAULT_COMPANY,
        priority: action.status === "overdue" ? "high" : "normal",
        plannedStart: meeting.date,
        dueDate: action.dueDate,
        status: action.status === "in_progress" ? "in_progress" : "open",
        meetingId: meeting.id,
        autoGenerated: true,
      });
    }
  }

  for (const rev of input.revisions) {
    if (rev.status !== "proposed") continue;
    const id = `auto-revision-${rev.id}`;
    if (dismissed.has(id)) continue;
    out.push({
      id,
      title: `Modification ${SCOPE_LABELS[rev.scope]} — ${rev.description.slice(0, 55)}`,
      description: rev.impact,
      origin: "plan_revision",
      sourceId: rev.id,
      roomCode: rev.roomCode,
      responsible: DEFAULT_RESPONSIBLE,
      company: DEFAULT_COMPANY,
      priority: rev.scope === "plan" ? "high" : "normal",
      plannedStart: rev.date,
      dueDate: addDays(rev.date, 14),
      status: "open",
      autoGenerated: true,
    });
  }

  for (const line of input.boq) {
    if (line.paymentRequested <= line.paymentApproved) continue;
    const id = `auto-budget-${line.id}`;
    if (dismissed.has(id)) continue;
    out.push({
      id,
      title: `Validation paiement — ${line.description.slice(0, 55)}`,
      description: `Demandé ${line.paymentRequested} · approuvé ${line.paymentApproved} · ${line.code}`,
      origin: "budget",
      sourceId: line.id,
      lotCode: line.lotCode,
      responsible: ROLE_OPC,
      company: DEFAULT_COMPANY,
      priority: "high",
      plannedStart: daysFromNow(0),
      dueDate: addDays(daysFromNow(0), 7),
      status: "open",
      autoGenerated: true,
    });
  }

  for (const res of input.reserves) {
    if (["closed", "levée"].includes(res.status)) continue;
    const id = `auto-reserve-${res.id}`;
    if (dismissed.has(id)) continue;
    out.push({
      id,
      title: `Réserve ${res.number} — ${res.title}`,
      description: res.correctiveAction || res.description,
      origin: res.type?.toLowerCase().includes("visite") ? "report" : "reserve",
      sourceId: res.id,
      roomCode: res.roomCode,
      lotCode: res.lotCode,
      responsible: res.assignedTo || DEFAULT_RESPONSIBLE,
      company: res.company || DEFAULT_COMPANY,
      priority:
        res.severity === "critical"
          ? "critical"
          : res.severity === "major"
            ? "high"
            : "normal",
      plannedStart: res.date,
      dueDate: res.dueDate,
      status: "open",
      reserveId: res.id,
      autoGenerated: true,
    });
  }

  return out;
}

export function syncActionTasks(
  existing: NassibActionTask[],
  dismissedIds: string[],
  input: Omit<Parameters<typeof buildActionTasksFromProject>[0], "dismissedIds">,
): NassibActionTask[] {
  return mergeExisting(
    buildActionTasksFromProject({ ...input, dismissedIds }),
    existing,
    new Set(dismissedIds),
  );
}

export type ActionTaskKpis = ReturnType<typeof actionTaskKpis>;

export function actionTaskKpis(tasks: NassibActionTask[]) {
  const open = tasks.filter((t) => !["done", "cancelled"].includes(t.status));
  return {
    total: tasks.length,
    open: open.length,
    done: tasks.filter((t) => t.status === "done").length,
    blocked: tasks.filter((t) => t.status === "blocked").length,
    critical: open.filter((t) => t.priority === "critical").length,
    withRoom: tasks.filter((t) => t.roomCode).length,
    withLot: tasks.filter((t) => t.lotCode).length,
    auto: tasks.filter((t) => t.autoGenerated).length,
    manual: tasks.filter((t) => !t.autoGenerated).length,
    byOrigin: (
      [
        "meeting",
        "report",
        "budget",
        "plan_revision",
        "reserve",
        "element",
        "manual",
      ] as const
    ).map((origin) => ({
      origin,
      count: tasks.filter((t) => t.origin === origin).length,
    })),
  };
}

export const ACTION_TASK_ORIGIN_LABELS: Record<NassibActionTask["origin"], string> = {
  manual: "Manuelle",
  meeting: "CR réunion",
  report: "Rapport visite",
  budget: "Validation budget",
  plan_revision: "Modification plan",
  reserve: "Réserve",
  element: "Ajout élément",
};

export const ACTION_TASK_STATUS_LABELS: Record<NassibActionTask["status"], string> = {
  open: "À faire",
  in_progress: "En cours",
  blocked: "Bloquée",
  done: "Terminée",
  cancelled: "Annulée",
};
