"use server";

import {
  updateActionTask,
  addActionTask,
  deleteActionTask,
  refreshActionTasksStore,
} from "@/lib/nassib";
import type { NassibActionTask } from "@/types/nassib";
import { revalidatePath } from "next/cache";

export async function updateActionTaskAction(
  id: string,
  patch: Partial<
    Pick<
      NassibActionTask,
      | "status"
      | "priority"
      | "responsible"
      | "dueDate"
      | "comments"
      | "title"
      | "description"
    >
  >,
) {
  const ok = updateActionTask(id, patch);
  revalidatePath("/taches");
  revalidatePath("/locaux");
  revalidatePath("/reunions");
  return { ok };
}

export async function addActionTaskAction(
  item: Omit<NassibActionTask, "id" | "autoGenerated" | "origin">,
) {
  addActionTask(item);
  revalidatePath("/taches");
  return { ok: true as const };
}

export async function deleteActionTaskAction(id: string) {
  const ok = deleteActionTask(id);
  revalidatePath("/taches");
  revalidatePath("/locaux");
  return { ok };
}

export async function refreshActionTasksAction() {
  refreshActionTasksStore();
  revalidatePath("/taches");
  return { ok: true as const };
}
