"use client";

import { useMemo, useState, useTransition } from "react";
import { Plus, X } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import {
  MeetingKpiRow,
  MeetingSection,
  ViewModeToggle,
} from "@/components/reunions/meeting-cards";
import {
  draftToMeetingCr,
  generateWeeklyMeetingDraft,
  shouldAutoGenerateDraft,
  type WeeklyMeetingDraft,
} from "@/lib/meetings/weekly-template";
import { meetingPrepCategoryLabel } from "@/lib/meetings/preparation-items";
import {
  formatMeetingDate,
  meetingKpis,
  MEETING_CATEGORY_LABELS,
  splitMeetingsByTime,
} from "@/lib/meetings/meeting-stats";
import type { Meeting, PlanningTask } from "@/types/nassib";
import { formatDate } from "@/lib/utils";

function MeetingDetailPanel({
  meeting,
  onClose,
}: {
  meeting: Meeting;
  onClose: () => void;
}) {
  return (
    <Card className="border-[#0891B2]/30">
      <CardHeader className="flex flex-row items-start justify-between gap-4">
        <div>
          <div className="mb-2 flex flex-wrap gap-2">
            <Badge variant="brand">{MEETING_CATEGORY_LABELS[meeting.category]}</Badge>
            <Badge variant={meeting.status === "planned" ? "default" : "success"}>
              {meeting.status === "planned" ? "Planifiée" : "Terminée"}
            </Badge>
            <Badge variant="info">{meeting.reference}</Badge>
          </div>
          <CardTitle className="text-[#003F72]">{meeting.title}</CardTitle>
          <p className="mt-1 text-sm text-slate-500">
            {formatMeetingDate(meeting.date)} · {meeting.location}
          </p>
        </div>
        <Button variant="outline" size="sm" onClick={onClose}>
          <X className="h-4 w-4" />
        </Button>
      </CardHeader>
      <CardContent className="space-y-4 text-sm">
        <div>
          <p className="mb-1 font-medium text-slate-700">Participants</p>
          <p className="text-slate-600">{meeting.participants.join(" · ")}</p>
        </div>
        {meeting.decisions.length > 0 && (
          <div>
            <p className="mb-1 font-medium text-slate-700">Décisions</p>
            <ul className="list-inside list-disc text-slate-600">
              {meeting.decisions.map((d) => (
                <li key={d}>{d}</li>
              ))}
            </ul>
          </div>
        )}
        {meeting.blockingPoints.length > 0 && (
          <div className="rounded-lg bg-red-50 p-3 text-red-900">
            {meeting.blockingPoints.map((b) => (
              <p key={b}>⚠ {b}</p>
            ))}
          </div>
        )}
        {meeting.actions.length > 0 && (
          <div>
            <p className="mb-2 font-medium text-slate-700">
              Actions ({meeting.actions.length})
            </p>
            <ul className="space-y-2">
              {meeting.actions.map((a) => (
                <li
                  key={a.id}
                  className="flex flex-wrap items-center justify-between gap-2 rounded-lg border p-2"
                >
                  <span>{a.description}</span>
                  <div className="flex items-center gap-2">
                    <span className="text-xs text-slate-500">{a.responsible}</span>
                    <Badge
                      variant={
                        a.status === "overdue"
                          ? "danger"
                          : a.status === "done"
                            ? "success"
                            : "warning"
                      }
                    >
                      {a.status === "overdue"
                        ? "En retard"
                        : a.status === "done"
                          ? "Fait"
                          : "En cours"}
                    </Badge>
                  </div>
                </li>
              ))}
            </ul>
          </div>
        )}
      </CardContent>
    </Card>
  );
}

function NewMeetingForm({
  draft,
  setDraft,
  onGenerate,
  onClose,
  pending,
}: {
  draft: WeeklyMeetingDraft;
  setDraft: React.Dispatch<React.SetStateAction<WeeklyMeetingDraft>>;
  onGenerate: () => void;
  onClose: () => void;
  pending: boolean;
}) {
  const autoHint = shouldAutoGenerateDraft();

  function updateField(id: string, value: string) {
    setDraft((d) => ({
      ...d,
      fields: d.fields.map((f) => (f.id === id ? { ...f, value } : f)),
    }));
  }

  function toggleCheck(id: string) {
    setDraft((d) => ({
      ...d,
      checklist: d.checklist.map((c) =>
        c.id === id ? { ...c, checked: !c.checked } : c,
      ),
    }));
  }

  return (
    <Card className="border-[#0891B2]/30">
      <CardHeader className="flex flex-row items-start justify-between gap-4">
        <div>
          <CardTitle className="text-[#003F72]">
            Nouvelle réunion — samedi {formatDate(draft.meetingDate)}
          </CardTitle>
          <p className="text-sm text-slate-500">
            N°{String(draft.meetingNumber).padStart(2, "0")}
            {autoHint && " · Modèle auto vendredi soir"}
          </p>
        </div>
        <Button variant="outline" size="sm" onClick={onClose}>
          <X className="h-4 w-4" />
        </Button>
      </CardHeader>
      <CardContent className="space-y-6">
        {draft.preparationItems.length > 0 && (
          <div className="rounded-xl border border-[#F97316]/40 bg-[#F97316]/5 p-4">
            <p className="mb-3 text-xs font-semibold uppercase tracking-wide text-[#F97316]">
              Éléments à préparer
            </p>
            <ul className="space-y-2 text-sm">
              {draft.preparationItems.map((item) => (
                <li key={item.id} className="rounded-lg bg-white p-3">
                  <div className="flex flex-wrap items-start justify-between gap-2">
                    <p className="font-medium text-[#003F72]">{item.title}</p>
                    <Badge variant="warning" className="text-[10px]">
                      {meetingPrepCategoryLabel(item.category)}
                    </Badge>
                  </div>
                  <p className="mt-1 text-slate-600">{item.detail}</p>
                </li>
              ))}
            </ul>
          </div>
        )}

        <div>
          <p className="mb-2 text-xs font-medium uppercase text-slate-500">
            Points à valider
          </p>
          <div className="grid gap-2 sm:grid-cols-2">
            {draft.checklist.map((c) => (
              <label
                key={c.id}
                className="flex cursor-pointer items-center gap-2 rounded-lg border p-3 text-sm"
              >
                <input
                  type="checkbox"
                  checked={c.checked}
                  onChange={() => toggleCheck(c.id)}
                />
                {c.label}
              </label>
            ))}
          </div>
        </div>

        <div className="space-y-4">
          {draft.fields.map((f) => (
            <div key={f.id}>
              <label className="mb-1 block text-sm font-medium text-slate-700">
                {f.label}
                {f.required && <span className="text-red-500"> *</span>}
              </label>
              {f.id === "f1" ? (
                <Input
                  placeholder="MOA, OPC, entreprises… (séparés par virgule)"
                  value={f.value}
                  onChange={(e) => updateField(f.id, e.target.value)}
                />
              ) : (
                <Textarea
                  rows={3}
                  value={f.value}
                  onChange={(e) => updateField(f.id, e.target.value)}
                />
              )}
            </div>
          ))}
        </div>

        <Button onClick={onGenerate} disabled={pending}>
          Générer le CR du jour
        </Button>
      </CardContent>
    </Card>
  );
}

export function ReunionsWorkspace({
  meetings: initialMeetings,
  tasks,
}: {
  meetings: Meeting[];
  tasks: PlanningTask[];
}) {
  const [meetings, setMeetings] = useState(initialMeetings);
  const [viewMode, setViewMode] = useState<"cards" | "list">("cards");
  const [selected, setSelected] = useState<Meeting | null>(null);
  const [showNewForm, setShowNewForm] = useState(false);
  const [generated, setGenerated] = useState<Meeting | null>(null);
  const [pending, startTransition] = useTransition();

  const initialDraft = useMemo(
    () => generateWeeklyMeetingDraft(tasks, meetings),
    [tasks, meetings],
  );
  const [draft, setDraft] = useState<WeeklyMeetingDraft>(initialDraft);

  const kpis = useMemo(() => meetingKpis(meetings), [meetings]);
  const { upcoming, past } = useMemo(
    () => splitMeetingsByTime(meetings),
    [meetings],
  );

  function generateCr() {
    startTransition(() => {
      const cr = draftToMeetingCr(initialDraft, draft);
      setGenerated(cr);
      setMeetings((prev) => [cr, ...prev]);
      setShowNewForm(false);
      setSelected(cr);
    });
  }

  return (
    <div className="space-y-6">
      <div className="flex flex-wrap items-start justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold text-[#003F72]">
            Réunions de Chantier
          </h1>
          <p className="mt-1 text-sm text-slate-500">
            Suivi des réunions et actions du chantier
          </p>
        </div>
        <Button
          className="bg-[#003F72] hover:bg-[#003F72]/90"
          onClick={() => {
            setShowNewForm(true);
            setSelected(null);
            setDraft(generateWeeklyMeetingDraft(tasks, meetings));
          }}
        >
          <Plus className="mr-2 h-4 w-4" />
          Nouvelle Réunion
        </Button>
      </div>

      <MeetingKpiRow kpis={kpis} />

      <ViewModeToggle mode={viewMode} onChange={setViewMode} />

      {showNewForm && (
        <NewMeetingForm
          draft={draft}
          setDraft={setDraft}
          onGenerate={generateCr}
          onClose={() => setShowNewForm(false)}
          pending={pending}
        />
      )}

      {selected && !showNewForm && (
        <MeetingDetailPanel meeting={selected} onClose={() => setSelected(null)} />
      )}

      {generated && !showNewForm && !selected && (
        <Card className="border-emerald-200 bg-emerald-50/50">
          <CardContent className="flex items-center justify-between gap-4 py-4 text-sm">
            <p className="text-emerald-900">
              CR généré : <strong>{generated.title}</strong>
            </p>
            <Button
              variant="outline"
              size="sm"
              onClick={() => setSelected(generated)}
            >
              Voir le détail
            </Button>
          </CardContent>
        </Card>
      )}

      <MeetingSection
        title="À venir"
        meetings={upcoming}
        viewMode={viewMode}
        onSelect={(m) => {
          setSelected(m);
          setShowNewForm(false);
        }}
      />

      <MeetingSection
        title="Passées"
        meetings={past}
        viewMode={viewMode}
        onSelect={(m) => {
          setSelected(m);
          setShowNewForm(false);
        }}
      />
    </div>
  );
}
